apiVersion: v1
kind: Service
metadata:
  name: devops-may-cry-metallb
  namespace: traffic-lab
  labels:
    app.kubernetes.io/name: devops-may-cry
spec:
  # В облаке такой Service обслуживает интеграция провайдера. В нашем
  # self-managed кластере внешний адрес ему назначит MetalLB.
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: devops-may-cry
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
